name: ${project.artifactId}
main: com.jaoafa.Dangerous.Main
version: ${project.version}
description: 2019年08月サバイバルイベントプラグイン
database: true
api-version: 1.13
softdepend: []
author: mine_book000
commands:
   selectmain:
      description: メインサーバの選択ができます。
      usage: /<command>
      permission: dangerous.selectmain
      permission-message: You do not have permission to perform this command.
   dangerous:
      description: Dangerousプラグインの設定等が変更できます。
      usage: /<command>
      permission: dangerous.dangerous
      permission-message: You do not have permission to perform this command.
   management:
      description: プラグインの制御等を行います。
      usage: /<command>
      permission: dangerous.management
      permission-message: You do not have permission to perform this command.
   g:
      description: ゲームモードを変更します。
      usage: |-
        /g: クリエイティブモードならスペクテイターモードに、スペクテイターモードならクリエイティブモードに、それ以外ならクリエイティブモードに変更します。
        /g <0-3>: 指定された数値に合うゲームモードに変更します。
        /g <0-3> <Player>: 指定したプレイヤーのゲームモードを指定された数値に合うゲームモードに変更します。
      permission: dangerous.g
      permission-message: You do not have permission to perform this command.
   h:
      description: /h bubu (FruitServer)
      usage: /<command> bubu
      permission: dangerous.h
      permission-message: You do not have permission to perform this command.
   hat:
      description: 手に持っているブロックを頭に載せます。
      usage: /<command>
      permission: dangerous.hat
      permission-message: You do not have permission to perform this command.
   waitstop:
      description: サーバオンラインプレイヤーが0人になったときに停止するかどうかを変更できます。
      usage: /<command>
      permission: dangerous.waitstop
      permission-message: You do not have permission to perform this command.
   pvp:
      description: PvPを有効/無効化します。
      usage: /<command>
      permission: dangerous.pvp
      permission-message: You do not have permission to perform this command.
   jp:
      description: かな変換を有効化・無効化します。
      usage: /<command>
      permission: dangerous.jp
      permission-message: You do not have permission to perform this command.